package com.paypal.esrenyxblrp.common;

public enum Status {
	NEWLY_ADDED,
	REMOVED,
	REMOVAL_INPROGRESS,
	SUNSETTING,
	INPROGRESS_IMMEDIATE_FOLLOWUP,
	INPROGRESS_SCHEDULED_FOLLOWUP,
	INPROGRESS_AWAITING_RESPONSE,
	CANNOT_BE_REMOVED
}
